# Generated by Django 5.0.6 on 2024-06-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_recipientage_request_recipientgender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='bldRequiredBeforeTime',
        ),
        migrations.RemoveField(
            model_name='request',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='request',
            name='recipientGender',
        ),
        migrations.RemoveField(
            model_name='request',
            name='unitsNeeded',
        ),
    ]
